### ISSUE TITLE
is it possible to alter the message senders nick in the main message part of the screen?

### ISSUE THREAD

**Issue by BrianGilbert** [ryanflorence/limescripts#6]
I'm trying to turn the nick into a url link that uses the nick as part of the link. I can't see a way to split that part of the message to edit it before being sent to the limechat window..

**Comment by ryanflorence** [comment]
classNames are published, and the "nick" element has the class "sender", so you ought to be able to do something like:

``` js
bind('sender', function() {
  var nick = this.innerHTML.replace(':', '');
  var url = "http://example.com/" + nick;
  this.innerHTML = '<a href="' + url + '">' + nick + '</a>';
});
```
